// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rvjycrapllupubyieqae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2anljcmFwbGx1cHVieWllcWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMzA3MTUsImV4cCI6MjA4NzgwNjcxNX0.CY9wNm4Tp-0CAURB4rPOZPKRwcBnQoOmUwRTGcnEWX0";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);